;;; diogenes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from diogenes.el

(autoload 'diogenes-search-tlg "diogenes" "\
Search for a phrase in the Greek TLG database.
Uses the Diogenes Perl Module.

(fn OPTIONS-OR-PATTERN &optional AUTHOR-PLIST PREFIX)" t)
(autoload 'diogenes-search-phi "diogenes" "\
Search for a phrase in the Latin PHI database.
Uses the Diogenes Perl Module.

(fn OPTIONS-OR-PATTERN &optional AUTHOR-PLIST PREFIX)" t)
(autoload 'diogenes-search-ddp "diogenes" "\
Search for a phrase in the Duke Documentary Papyri.
Uses the Diogenes Perl module.

(fn OPTIONS-OR-PATTERN &optional AUTHOR-PLIST PREFIX)" t)
(autoload 'diogenes-search-ins "diogenes" "\
Search for a phrase in the Classical Inscriptions Database.
Uses the Diogenes Perl module.

(fn OPTIONS-OR-PATTERN &optional AUTHOR-PLIST PREFIX)" t)
(autoload 'diogenes-search-chr "diogenes" "\
Search for a phrase in the Christian Inscriptions Database.
Uses the Diogenes Perl module.

(fn OPTIONS-OR-PATTERN &optional AUTHOR-PLIST PREFIX)" t)
(autoload 'diogenes-search-misc "diogenes" "\
Search for a phrase in the Miscellaneous PHI Texts Database.
Uses the Diogenes Perl module.

(fn OPTIONS-OR-PATTERN &optional AUTHOR-PLIST PREFIX)" t)
(autoload 'diogenes-search-cop "diogenes" "\
Search for a phrase in the PHI Coptic Texts Database.
Uses the Diogenes Perl module.

(fn OPTIONS-OR-PATTERN &optional AUTHOR-PLIST PREFIX)" t)
(autoload 'diogenes-dump-tlg "diogenes" "\
Dump a work from the Greek TLG database in its entirety.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-dump-phi "diogenes" "\
Dump a work from the Latin PHI database in its entirety.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-dump-ddp "diogenes" "\
Dump a work from the Duke Documentary Database in its entirety.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-dump-ins "diogenes" "\
Dump a work from the Classical Inscriptions Database in its entirety.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-dump-chr "diogenes" "\
Dump a work from the Christian Inscriptions Database in its entirety.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-dump-misc "diogenes" "\
Dump a work from the Miscellaneous PHI Texts Database in its entirety.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-dump-cop "diogenes" "\
Dump a work from the PHI Coptic Texts Database in its entirety.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-browse-tlg "diogenes" "\
Browse a specific passage in a work from the Greek TLG database.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-browse-phi "diogenes" "\
Browse a work from the Latin PHI database.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-browse-ddp "diogenes" "\
Browse a work from the Duke Documentary Database.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-browse-ins "diogenes" "\
Browse a work from the Classical Inscriptions Database.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-browse-chr "diogenes" "\
Browse a work from the Christian Inscriptions Database.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-browse-misc "diogenes" "\
Browse a work from the Miscellaneous PHI Texts  Database.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-browse-cop "diogenes" "\
Browse a work from the  PHI Coptic Texts Database.
Uses the Diogenes Perl module.

(fn &optional AUTHOR WORK)" t)
(autoload 'diogenes-lookup-greek "diogenes" "\
Search for a greek word in the LSJ Greek Dictionary.
Accepts both Unicode and Beta Code as input.

(fn WORD)" t)
(autoload 'diogenes-lookup-latin "diogenes" "\
Search for a greek word in the Lewis & Short Latin Dictionary.

(fn WORD)" t)
(autoload 'diogenes-parse-and-lookup-greek "diogenes" "\
Try to parse a greek word and look it up.

(fn WORD)" t)
(autoload 'diogenes-parse-and-lookup-latin "diogenes" "\
Try to parse a latin word and look it up.

(fn WORD)" t)
(autoload 'diogenes-parse-greek "diogenes" "\
Parse a greek word and display the results.
QUERY is interpreted as a regular expression which must match the forms.

(fn QUERY)" t)
(autoload 'diogenes-parse-latin "diogenes" "\
Parse a latin word and display the results.
QUERY is interpreted as a regular expression which must match the forms.

(fn QUERY)" t)
(autoload 'diogenes-show-all-forms-greek "diogenes" "\
Show all attested forms of a Greek lemma.

(fn LEMMA)" t)
(autoload 'diogenes-show-all-forms-latin "diogenes" "\
Show all attested forms of a Latin lemma.

(fn LEMMA)" t)
(autoload 'diogenes-show-all-lemmata-greek "diogenes" "\
Show all Greek lemmata and forms that match QUERY.

(fn QUERY)" t)
(autoload 'diogenes-show-all-lemmata-latin "diogenes" "\
Show all Latin lemmata and forms that match QUERY.

(fn QUERY)" t)
(autoload 'diogenes-utf8-to-beta "diogenes" "\
Convert greek beta code to utf-8. 
If a region is active, convert the contents of the region in place; 
otherwise, prompt the user for input.

(fn STR)" t)
(autoload 'diogenes-beta-to-utf8 "diogenes" "\
Convert greek unicode to beta code.
If a region is active, convert the contents of the region in place; 
otherwise, prompt the user for input.

(fn STR)" t)
(autoload 'diogenes-strip-diacritics "diogenes" "\
Remove all diacritics in the active region.

(fn START END)" t)
(autoload 'diogenes-ol-to-ad "diogenes" "\
Converts Ol. to A.D.

(fn OL)" t)
(autoload 'diogenes-ad-to-ol "diogenes" "\
Converts A.D. to Ol.

(fn AD)" t)
 (autoload 'diogenes "diogenes" nil t)
(register-definition-prefixes "diogenes" '("diogenes-"))


;;; Generated autoloads from diogenes-archive.el

(autoload 'diogenes-utf8-to-beta-with-perl "diogenes-archive" "\
Call perl to convert greek beta code to utf-8. 
If a region is active, convert the contents of the region in place; 
otherwise, prompt the user for input.

(fn STR)" t)
(autoload 'diogenes-beta-to-utf8-with-perl "diogenes-archive" "\
Call perl to convert greek unicode to beta code.
If a region is active, convert the contents of the region in place; 
otherwise, prompt the user for input.

(fn STR)" t)
(register-definition-prefixes "diogenes-archive" '("diogenes-"))


;;; Generated autoloads from diogenes-browser.el

(register-definition-prefixes "diogenes-browser" '("diogenes-"))


;;; Generated autoloads from diogenes-corpora.el

(register-definition-prefixes "diogenes-corpora" '("diogenes-"))


;;; Generated autoloads from diogenes-forms.el

(register-definition-prefixes "diogenes-forms" '("diogenes-"))


;;; Generated autoloads from diogenes-legacy.el

(autoload 'diogenes-delete-line-numbers "diogenes-legacy" "\
Delete line numbers, starting at point" t)
(autoload 'diogenes-tidy-up-search-results "diogenes-legacy" "\
Post-processes search results of diogenes" t)


;;; Generated autoloads from diogenes-lisp-utils.el

(register-definition-prefixes "diogenes-lisp-utils" '("diogenes-"))


;;; Generated autoloads from diogenes-perl-interface.el

(register-definition-prefixes "diogenes-perl-interface" '("diogenes--"))


;;; Generated autoloads from diogenes-perseus.el

(register-definition-prefixes "diogenes-perseus" '("diogenes-"))


;;; Generated autoloads from diogenes-search.el

(register-definition-prefixes "diogenes-search" '("diogenes-"))


;;; Generated autoloads from diogenes-user-interface.el

(register-definition-prefixes "diogenes-user-interface" '("diogenes--select-"))


;;; Generated autoloads from diogenes-utils.el

(autoload 'diogenes-iota-subscript-to-adscript "diogenes-utils" "\
Convert all subscript iota into adscript ones in the current
buffer, or in the active region.

(fn BEGIN END)" t)
(autoload 'diogenes-remove-hyphenation "diogenes-utils" "\
Delete hyphenation in the active region, or until EOBP.

(fn &optional START END)" t)
(autoload 'diogenes-apostrophe "diogenes-utils" "\
Replace all greek apostrophes with the typographical correct ῾.

(fn &optional START END)" t)
(register-definition-prefixes "diogenes-utils" '("diogenes--"))

;;; End of scraped data

(provide 'diogenes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; diogenes-autoloads.el ends here
